/**
 * PlacementPlot AI — One-Command Database Setup
 * 
 * Prerequisites:
 *   1. Fill in your Supabase anon key and service role key below
 *      (from https://supabase.com/dashboard/project/mixoqvqwgyphubaktpwr/settings/api)
 *   2. Fill in your Gemini API key
 *      (from https://aistudio.google.com/app/apikey)
 *   3. Run: node setup.mjs
 * 
 * This script will:
 *   - Verify the database connection
 *   - Run the SQL migration (create tables, indexes, RPC functions)
 *   - Seed the knowledge base with embeddings via Gemini
 */

// ─────────────────────────────────────────────────────────────────────────
// 🔑 FILL THESE IN (get from Supabase dashboard > Project Settings > API)
// ─────────────────────────────────────────────────────────────────────────
const CONFIG = {
  supabaseUrl: "https://mixoqvqwgyphubaktpwr.supabase.co",
  anonKey: "",          // ← paste your anon/public key here
  serviceRoleKey: "",   // ← paste your service_role/secret key here
  geminiApiKey: "",     // ← paste your Gemini API key here
};
// ─────────────────────────────────────────────────────────────────────────

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = __dirname;

// ─── Step 0: Validate config ──────────────────────────────────────
function validateConfig() {
  if (!CONFIG.anonKey || CONFIG.anonKey.length < 100) {
    console.error("❌ Missing or invalid anonKey. Get it from:");
    console.error("   https://supabase.com/dashboard/project/mixoqvqwgyphubaktpwr/settings/api");
    process.exit(1);
  }
  if (!CONFIG.serviceRoleKey || CONFIG.serviceRoleKey.length < 100) {
    console.error("❌ Missing or invalid serviceRoleKey. Get it from:");
    console.error("   https://supabase.com/dashboard/project/mixoqvqwgyphubaktpwr/settings/api");
    process.exit(1);
  }
  if (!CONFIG.geminiApiKey || CONFIG.geminiApiKey.length < 20) {
    console.error("❌ Missing or invalid geminiApiKey. Get it from:");
    console.error("   https://aistudio.google.com/app/apikey");
    process.exit(1);
  }
  console.log("✅ Configuration validated");
}

// ─── Step 1: Write .env.local ─────────────────────────────────────
function writeEnvFile() {
  const envContent = `# ===== PlacementPlot AI — Local Environment Variables =====
# Generated by setup.mjs on ${new Date().toISOString()}

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${CONFIG.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${CONFIG.anonKey}
SUPABASE_SERVICE_ROLE_KEY=${CONFIG.serviceRoleKey}

# Google Gemini AI
GEMINI_API_KEY=${CONFIG.geminiApiKey}

# Razorpay (optional — mock checkout works without these)
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

  writeFileSync(resolve(ROOT, ".env.local"), envContent, "utf8");
  console.log("✅ .env.local written successfully");
}

// ─── Step 2: Test Supabase connection ─────────────────────────────
async function testConnection() {
  const res = await fetch(`${CONFIG.supabaseUrl}/rest/v1/`, {
    headers: {
      "apikey": CONFIG.anonKey,
      "Authorization": `Bearer ${CONFIG.anonKey}`,
    },
  });

  if (res.ok || res.status === 200) {
    console.log("✅ Supabase connection successful");
    return true;
  }
  
  const body = await res.text();
  console.error(`❌ Supabase connection failed (${res.status}): ${body}`);
  return false;
}

// ─── Step 3: Apply SQL migration via Supabase SQL API ─────────────
async function applyMigration() {
  console.log("\n📋 Applying database migration...");
  
  const sqlPath = resolve(ROOT, "supabase", "migrations", "001_vector_tables.sql");
  const sql = readFileSync(sqlPath, "utf8");
  
  // Split into individual statements for execution
  const statements = sql
    .split(";")
    .map(s => s.trim())
    .filter(s => s.length > 0 && !s.startsWith("--"));

  let successCount = 0;
  let skipCount = 0;
  
  for (const statement of statements) {
    if (!statement) continue;
    
    const res = await fetch(`${CONFIG.supabaseUrl}/rest/v1/rpc/exec_sql`, {
      method: "POST",
      headers: {
        "apikey": CONFIG.serviceRoleKey,
        "Authorization": `Bearer ${CONFIG.serviceRoleKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ sql: statement + ";" }),
    });

    if (res.ok) {
      successCount++;
    } else {
      const body = await res.json().catch(() => ({}));
      // Ignore "already exists" errors - idempotent
      if (body?.message?.includes("already exists") || body?.code === "42710" || body?.code === "42P07") {
        skipCount++;
      } else {
        console.warn(`   ⚠️  Statement warning: ${body?.message || res.status}`);
      }
    }
  }

  console.log(`✅ Migration applied (${successCount} executed, ${skipCount} already existed)`);
}

// ─── Step 4: Verify tables exist ──────────────────────────────────
async function verifyTables() {
  const tables = ["documents", "profiles", "resumes", "mock_interviews", "subscriptions"];
  
  for (const table of tables) {
    const res = await fetch(`${CONFIG.supabaseUrl}/rest/v1/${table}?select=id&limit=1`, {
      headers: {
        "apikey": CONFIG.serviceRoleKey,
        "Authorization": `Bearer ${CONFIG.serviceRoleKey}`,
      },
    });
    
    if (res.ok || res.status === 200) {
      console.log(`   ✅ Table '${table}' exists`);
    } else {
      const body = await res.json().catch(() => ({}));
      if (body?.code === "42P01") {
        console.error(`   ❌ Table '${table}' does NOT exist — migration may have failed`);
        console.error("   → Run the SQL manually at:");
        console.error("     https://supabase.com/dashboard/project/mixoqvqwgyphubaktpwr/sql/new");
      }
    }
  }
}

// ─── Step 5: Seed knowledge base ──────────────────────────────────
async function seedKnowledgeBase() {
  console.log("\n📚 Seeding knowledge base (this generates embeddings via Gemini — may take ~60s)...");
  
  // Check if dev server is running
  let devServerRunning = false;
  try {
    const pingRes = await fetch("http://localhost:3000/api/seed", { method: "HEAD" });
    devServerRunning = true;
  } catch {
    devServerRunning = false;
  }

  if (!devServerRunning) {
    console.log("⚠️  Dev server not detected on localhost:3000");
    console.log("   Start it with: npm run dev");
    console.log("   Then call the seed endpoint: http://localhost:3000/api/seed");
    return;
  }

  const res = await fetch("http://localhost:3000/api/seed", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    console.error("❌ Seeding failed:", body.error || body.details || res.status);
    return;
  }

  const data = await res.json();
  if (data.success) {
    console.log(`✅ Knowledge base seeded! ${data.totalIndexed} documents indexed`);
    for (const [kb, count] of Object.entries(data.details || {})) {
      console.log(`   • ${kb}: ${count} docs`);
    }
  } else {
    console.error("❌ Seeding error:", data.error);
  }
}

// ─── Main ──────────────────────────────────────────────────────────
async function main() {
  console.log("╔═══════════════════════════════════════════════╗");
  console.log("║   PlacementPlot AI — Database Setup Script    ║");
  console.log("╚═══════════════════════════════════════════════╝\n");

  // Validate
  validateConfig();

  // Write env file
  console.log("\n📝 Writing .env.local...");
  writeEnvFile();

  // Test connection
  console.log("\n🔌 Testing Supabase connection...");
  const connected = await testConnection();
  if (!connected) process.exit(1);

  // Apply migration
  await applyMigration();

  // Verify tables
  console.log("\n🔍 Verifying tables...");
  await verifyTables();

  // Seed
  await seedKnowledgeBase();

  console.log("\n╔═══════════════════════════════════════════════╗");
  console.log("║         ✅  SETUP COMPLETE!                    ║");
  console.log("╠═══════════════════════════════════════════════╣");
  console.log("║  Your app is ready. Restart the dev server:   ║");
  console.log("║     npm run dev                               ║");
  console.log("║  Then open: http://localhost:3000             ║");
  console.log("╚═══════════════════════════════════════════════╝");
}

main().catch((err) => {
  console.error("\n💥 Setup failed:", err.message);
  process.exit(1);
});
