"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import Hls from "hls.js";
import { ArrowRight, Menu, X, Check, Brain, Award, Calendar, Sparkles } from "lucide-react";
import { supabase } from "@/lib/supabase";

export default function Home() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    const checkUser = async () => {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (user) setIsLoggedIn(true);
      } catch (err) {
        console.error("Auth check failed:", err);
      }
    };
    checkUser();

    const video = videoRef.current;
    if (!video) return;

    const streamUrl = "https://stream.mux.com/tLkHO1qZoaaQOUeVWo8hEBeGQfySP02EPS02BmnNFyXys.m3u8";

    if (video.canPlayType("application/vnd.apple.mpegurl")) {
      // For Safari native playback
      video.src = streamUrl;
    } else if (Hls.isSupported()) {
      const hls = new Hls({ enableWorker: false });
      hls.loadSource(streamUrl);
      hls.attachMedia(video);
      return () => {
        hls.destroy();
      };
    }
  }, []);

  const navLinks = [
    { label: "RESUME", href: "#resume-score" },
    { label: "INTERVIEWS", href: "#mock-interviews" },
    { label: "ROADMAPS", href: "#roadmaps" },
    { label: "COMPANIES", href: "#companies" },
    { label: "PRICING", href: "#pricing" },
  ];

  const features = [
    {
      icon: <Award className="w-5 h-5 text-[#5ed29c]" />,
      title: "ATS Resume Analyzer",
      description: "Extract text and analyze your resume against real ATS parsing rules and recruiter keywords to get a detailed compatibility score.",
      tag: "RAG-powered",
      link: "/dashboard/resume",
      actionText: "Analyze Resume"
    },
    {
      icon: <Brain className="w-5 h-5 text-[#5ed29c]" />,
      title: "AI Mock Interviews",
      description: "Practice technical coding and behavioral rounds in real-time. Receive scoring on accuracy, communication, and problem-solving.",
      tag: "Interactive",
      link: "/dashboard/interview",
      actionText: "Start Interview"
    },
    {
      icon: <Sparkles className="w-5 h-5 text-[#5ed29c]" />,
      title: "Company prep banks",
      description: "Browse over 5,000+ real interview questions from TCS, Infosys, Cognizant, Google, and 30+ service/product companies.",
      tag: "30+ recruiters",
      link: "/dashboard/companies",
      actionText: "Browse Questions"
    },
    {
      icon: <Calendar className="w-5 h-5 text-[#5ed29c]" />,
      title: "Placement Roadmaps",
      description: "Receive week-by-week study planners generated by AI to close skill gaps, complete with direct resources and DSA trackers.",
      tag: "Personalized",
      link: "/dashboard/roadmap",
      actionText: "View Plan"
    }
  ];

  return (
    <main className="relative min-h-screen bg-[#070b0a] font-[family-name:var(--font-inter)] text-white overflow-x-hidden selection:bg-[#5ed29c]/20 selection:text-[#5ed29c]">
      
      {/* 1. BACKGROUND VIDEO & OVERLAYS */}
      <div className="absolute inset-0 w-full h-full z-0 overflow-hidden pointer-events-none">
        <video
          ref={videoRef}
          autoPlay
          loop
          muted
          playsInline
          className="w-full h-full object-cover opacity-60"
        />
        {/* Left-to-right dark gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#070b0a] via-[#070b0a]/70 to-transparent" />
        {/* Bottom-up dark gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-[#070b0a] via-[#070b0a]/40 to-transparent" />
      </div>

      {/* 2. VERTICAL GRID SYSTEM */}
      <div className="absolute inset-0 hidden md:flex pointer-events-none z-10 w-full max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="w-[25%] border-r border-white/5 h-full" />
        <div className="w-[25%] border-r border-white/5 h-full" />
        <div className="w-[25%] border-r border-white/5 h-full" />
        <div className="w-[25%] h-full" />
      </div>

      {/* 3. CENTRAL ELLIPSE GLOW */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-[350px] pointer-events-none z-10 overflow-hidden">
        <svg className="w-full h-full opacity-35" viewBox="0 0 1000 300" fill="none" xmlns="http://www.w3.org/2000/svg">
          <ellipse cx="500" cy="50" rx="420" ry="120" fill="url(#nestEllipseGlow)" filter="url(#nestBlurGlow)" />
          <defs>
            <linearGradient id="nestEllipseGlow" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#06b6d4" /> {/* Cyan */}
              <stop offset="100%" stopColor="#047857" /> {/* Dark Green */}
            </linearGradient>
            <filter id="nestBlurGlow">
              <feGaussianBlur stdDeviation="25" />
            </filter>
          </defs>
        </svg>
      </div>

      {/* 4. GLOBAL NAVIGATION */}
      <header className="sticky top-0 w-full z-40 bg-[#070b0a]/80 backdrop-blur-md border-b border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center gap-2 z-50">
            <div className="w-9 h-9 rounded-lg bg-[#5ed29c]/10 border border-[#5ed29c]/30 flex items-center justify-center shadow-lg shadow-[#5ed29c]/10">
              <span className="text-[#5ed29c] font-black text-lg">P</span>
            </div>
            <span className="text-xl font-bold tracking-tight text-white">
              Placement<span className="text-[#5ed29c]">Plot</span>
            </span>
          </Link>

          {/* Desktop Menu */}
          <nav className="hidden md:flex items-center gap-8">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                className="text-sm font-semibold tracking-wider text-gray-300 hover:text-[#5ed29c] transition-colors"
              >
                {link.label}
              </a>
            ))}
          </nav>

          {/* CTAs */}
          <div className="hidden md:flex items-center gap-4">
            {isLoggedIn ? (
              <Link 
                href="/dashboard" 
                className="bg-[#5ed29c] text-[#070b0a] font-bold text-sm tracking-wider rounded-full px-6 py-2.5 uppercase transition-all duration-300 shadow-lg shadow-[#5ed29c]/10 hover:scale-105"
              >
                DASHBOARD
              </Link>
            ) : (
              <>
                <Link 
                  href="/login" 
                  className="text-sm font-semibold text-gray-300 hover:text-white border border-white/10 rounded-full px-5 py-2 hover:bg-white/5 transition-all"
                >
                  LOG IN
                </Link>
                <Link 
                  href="/signup" 
                  className="bg-[#5ed29c] text-[#070b0a] font-bold text-sm tracking-wider rounded-full px-6 py-2.5 uppercase transition-transform hover:scale-105"
                >
                  GET STARTED
                </Link>
              </>
            )}
          </div>

          {/* Mobile Hamburger Button */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden p-2 text-gray-400 hover:text-white z-50 focus:outline-none"
            aria-label="Toggle Menu"
          >
            {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>
      </header>

      {/* MOBILE FULL-SCREEN OVERLAY MENU */}
      {mobileMenuOpen && (
        <div className="fixed inset-0 bg-[#070b0a] z-40 flex flex-col justify-center items-center p-6 animate-fade-in md:hidden">
          <nav className="flex flex-col items-center gap-8 mb-12">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                onClick={() => setMobileMenuOpen(false)}
                className="text-2xl font-bold tracking-wider text-gray-300 hover:text-[#5ed29c] transition-colors"
              >
                {link.label}
              </a>
            ))}
          </nav>
          <div className="flex flex-col gap-4 w-full max-w-xs">
            {isLoggedIn ? (
              <Link
                href="/dashboard"
                onClick={() => setMobileMenuOpen(false)}
                className="w-full text-center py-3 bg-[#5ed29c] text-[#070b0a] rounded-full font-bold uppercase"
              >
                DASHBOARD
              </Link>
            ) : (
              <>
                <Link
                  href="/login"
                  onClick={() => setMobileMenuOpen(false)}
                  className="w-full text-center py-3 border border-white/10 rounded-full text-white font-bold hover:bg-white/5"
                >
                  LOG IN
                </Link>
                <Link
                  href="/signup"
                  onClick={() => setMobileMenuOpen(false)}
                  className="w-full text-center py-3 bg-[#5ed29c] text-[#070b0a] rounded-full font-bold uppercase"
                >
                  GET STARTED
                </Link>
              </>
            )}
          </div>
        </div>
      )}

      {/* 5. HERO CONTAINER */}
      <section className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-32 z-20 flex flex-col items-center text-center">
        
        {/* LIQUID GLASS CARD */}
        <div className="liquid-glass w-[200px] h-[200px] rounded-3xl p-6 flex flex-col justify-between items-center text-center translate-y-[-50px] shadow-2xl transition-transform hover:scale-105 duration-500 z-30">
          <span className="text-[14px] text-gray-400 font-semibold tracking-wider">
            [ 2025 ]
          </span>
          <h4 className="text-[18px] font-medium leading-tight text-white">
            Taught by <span className="font-[family-name:var(--font-serif)] italic text-[#5ed29c]">Industry</span> Professionals
          </h4>
          <p className="text-[11px] text-gray-400 leading-normal">
            Optimized for top placement outcomes.
          </p>
        </div>

        {/* HERO CONTENT */}
        <div className="flex flex-col items-center max-w-4xl mt-4">
          {/* Eyebrow */}
          <span className="font-[family-name:var(--font-jakarta)] font-bold text-[11px] tracking-widest text-[#5ed29c] uppercase mb-4">
            Career-Ready Curriculum
          </span>

          {/* Title */}
          <h1 className="font-extrabold uppercase tracking-tight text-white leading-[1.05] mb-6 text-4xl sm:text-6xl md:text-7xl">
            LAUNCH YOUR PLACEMENT CAREER<span className="text-[#5ed29c]">.</span>
          </h1>

          {/* Description */}
          <p className="text-gray-400 font-normal leading-relaxed text-sm md:text-base max-w-[512px] opacity-70 mb-8">
            Master in-demand coding skills, optimize your resume for ATS with RAG, and practice mock interviews built on real company questions.
          </p>

          {/* CTA Button */}
          <Link 
            href={isLoggedIn ? "/dashboard" : "/signup"} 
            className="group inline-flex items-center gap-3 bg-[#5ed29c] text-[#070b0a] font-bold text-sm sm:text-base tracking-wider rounded-full py-3.5 px-8 uppercase transition-all duration-300 shadow-xl shadow-[#5ed29c]/10 hover:shadow-[#5ed29c]/20 hover:scale-105"
          >
            {isLoggedIn ? "Go to Dashboard" : "Get Started"}
            <ArrowRight className="w-5 h-5 text-[#070b0a] transition-transform duration-300 group-hover:translate-x-1" />
          </Link>
        </div>

      </section>

      {/* 6. COLUMNS / FEATURES GRID */}
      <section id="features" className="relative border-t border-white/5 bg-[#070b0a]/90 py-24 z-20">
        <div className="absolute inset-0 bg-noise opacity-[0.03] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          <div className="text-center mb-16 max-w-2xl mx-auto">
            <span className="text-[11px] font-bold tracking-widest text-[#5ed29c] uppercase">
              Our Capabilities
            </span>
            <h2 className="text-3xl font-extrabold text-white mt-3 uppercase tracking-tight">
              STUDIO-GRADE WORKFLOWS FOR APPLICANTS.
            </h2>
            <p className="text-gray-400 text-sm mt-3">
              Four specialized placement assistants built using modern AI and real placement data.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feat, idx) => (
              <div
                key={idx}
                className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 flex flex-col justify-between hover:border-white/10 hover:bg-white/[0.03] transition-all duration-300 shadow-xl"
              >
                <div>
                  <div className="flex justify-between items-center mb-6">
                    <div className="w-10 h-10 rounded-lg bg-[#5ed29c]/10 border border-[#5ed29c]/20 flex items-center justify-center">
                      {feat.icon}
                    </div>
                    <span className="text-[10px] text-gray-500 font-bold uppercase tracking-wider">
                      {feat.tag}
                    </span>
                  </div>

                  <h3 className="text-lg font-bold text-white mb-2 uppercase">
                    {feat.title}
                  </h3>
                  <p className="text-gray-400 text-xs sm:text-sm leading-relaxed">
                    {feat.description}
                  </p>
                </div>

                <div className="mt-8">
                  <Link
                    href={isLoggedIn ? feat.link : "/signup"}
                    className="inline-flex items-center gap-1.5 text-xs font-bold text-[#5ed29c] hover:underline uppercase"
                  >
                    {feat.actionText}
                    <ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* 7. PRICING SECTION */}
      <section id="pricing" className="relative border-t border-white/5 bg-[#070b0a] py-24 z-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="mb-16">
            <span className="text-[11px] font-bold tracking-widest text-[#5ed29c] uppercase">
              Subscription
            </span>
            <h2 className="text-3xl font-extrabold text-white mt-3 uppercase tracking-tight">
              PRICING PLANS built for students.
            </h2>
          </div>

          <div className="grid lg:grid-cols-3 gap-8 max-w-5xl mx-auto text-left">
            
            {/* Free Plan */}
            <div className="bg-white/[0.01] border border-white/5 rounded-2xl p-8 flex flex-col justify-between shadow-xl">
              <div>
                <h3 className="text-xl font-bold text-white uppercase">FREE TIER</h3>
                <p className="text-gray-400 text-xs mt-2">Test out our core features with zero commitments.</p>
                <div className="my-8">
                  <span className="text-4xl font-extrabold text-white">₹0</span>
                  <span className="text-gray-500 text-sm"> / forever</span>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-gray-300">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    2 ATS Resume Analyses
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-gray-300">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    1 AI Mock Interview Session
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-gray-300">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Browse 5 Questions per Company
                  </li>
                </ul>
              </div>
              <Link 
                href={isLoggedIn ? "/dashboard" : "/signup"} 
                className="w-full text-center py-3 mt-8 bg-white/5 border border-white/10 rounded-xl font-bold text-xs hover:bg-white/10 text-white uppercase"
              >
                {isLoggedIn ? "Go to Dashboard" : "Sign Up Free"}
              </Link>
            </div>

            {/* Premium Plan */}
            <div className="bg-white/[0.02] border border-[#5ed29c]/30 rounded-2xl p-8 flex flex-col justify-between shadow-2xl relative">
              <div className="absolute top-0 right-8 -translate-y-1/2 bg-[#5ed29c] text-[#070b0a] font-black text-[10px] tracking-wider uppercase px-3.5 py-1 rounded-full">
                Most Popular
              </div>
              <div>
                <h3 className="text-xl font-bold text-white uppercase">PREMIUM</h3>
                <p className="text-gray-400 text-xs mt-2">Complete access to everything you need to get placed.</p>
                <div className="my-8">
                  <span className="text-4xl font-extrabold text-white">₹149</span>
                  <span className="text-gray-500 text-sm"> / month</span>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-white">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Unlimited Resume Scoring
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-white">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Unlimited Mock Interviews
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-white">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Personalized Placement Roadmap
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-white">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Unlock all 30+ Company Banks
                  </li>
                </ul>
              </div>
              <Link 
                href={isLoggedIn ? "/dashboard/billing" : "/signup"} 
                className="w-full text-center py-3 mt-8 bg-[#5ed29c] text-[#070b0a] rounded-xl font-bold text-xs hover:scale-105 transition-transform uppercase"
              >
                {isLoggedIn ? "Go to Billing" : "Upgrade Now"}
              </Link>
            </div>

            {/* Company Pack Plan */}
            <div className="bg-white/[0.01] border border-white/5 rounded-2xl p-8 flex flex-col justify-between shadow-xl">
              <div>
                <h3 className="text-xl font-bold text-white uppercase">INTERVIEW PACK</h3>
                <p className="text-gray-400 text-xs mt-2">Deep dive prep focused on a single target company.</p>
                <div className="my-8">
                  <span className="text-4xl font-extrabold text-white">₹99</span>
                  <span className="text-gray-500 text-sm"> / company</span>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-gray-300">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    50+ Selected Curated Questions
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-gray-300">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Hiring Process Breakdown
                  </li>
                  <li className="flex items-center gap-2.5 text-xs sm:text-sm text-gray-300">
                    <Check className="w-4 h-4 text-[#5ed29c] shrink-0" />
                    Targeted Company Mock Round
                  </li>
                </ul>
              </div>
              <Link 
                href={isLoggedIn ? "/dashboard/billing" : "/signup"} 
                className="w-full text-center py-3 mt-8 bg-white/5 border border-white/10 rounded-xl font-bold text-xs hover:bg-white/10 text-white uppercase"
              >
                Unlock Pack
              </Link>
            </div>

          </div>

        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-[#070b0a] border-t border-white/5 py-12 text-center text-xs text-gray-500 z-20 relative">
        <p>© 2026 PlacementPlot AI. All rights reserved. Built to empower Indian engineering students.</p>
      </footer>

    </main>
  );
}
